name: Chat-Auto

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
        
    - name: Deploy para o servidor CentOS
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: 10.251.1.52
        username: root
        key: '@tm@T3c'
    - name: Navegar para o diretório desejado
      run: cd /caminho/do/seu/diretorio

    - name: Inicializar um projeto npm
      run: npm init
           
  
