name: Chat-Auto

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v2
      with:
       submodules: 'recursive'
       runs-on: node-16
    - name: Deploy para o servidor CentOS
      uses: appleboy/ssh-action@master
      with:
        host: 179.131.10.193
        username: root
        password: '$tr@ng3!'
    - name: Transferir arquivos para o servidor
      run: |
          git clone https://github.com/developerErisson/Chat-Auto.git /var/www/backend/teste

    - name: Comandos de Deploy no servidor
      run: |
        ssh root@electro 'node src/server.js'

