name: Chat-Auto

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
        
    - name: Deploy para o servidor CentOS
      uses: appleboy/ssh-action@master
      with:
        host: 10.251.1.52
        username: root
        key: SHA256:qbt9VatE8sfvvLomjU4bKnHRQIxFjADQVI8r59/KrTE.
    - name: Navegar para o diretório desejado
      run: cd /caminho/do/seu/diretorio

    - name: Inicializar um projeto npm
      run: npm init
           
  
