name: Chat-Auto

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
        
    - name: Deploy para o servidor CentOS
      uses: appleboy/ssh-action@master
      with:
        host: 10.251.1.52
        username: root
        password: '@tm@T3c'
    - name: Transferir arquivos para o servidor
      run: |
          git clone https://github.com/developerErisson/Chat-Auto.git /var/www/backend/chat-auto
  
