name: Chat-Auto

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/setup-node@v2
      with:
        node-version: 16.18.1
    - name: Deploy para o servidor CentOS
      uses: appleboy/ssh-action@master
      with:
        host: 10.251.1.52
        username: root
        password: '@tm@T3c'
    - name: Transferir arquivos para o servidor
      run: |
          git clone https://github.com/developerErisson/Chat-Auto.git /var/www/backend/chat-auto

    - name: Comandos de Deploy no servidor
      run: |
        ssh root@electro 'node src/server.js'

