name: Chat-Auto

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
        
    - name: Deploy para o servidor CentOS
      uses: appleboy/ssh-action@v.0.1.2
      with:
        host: 10.251.1.52
        username: root
        password: '@tm@T3c'

           
  
