name: Chat-Auto

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
        
    - name: Deploy para o servidor CentOS
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: 10.251.1.52
        username: root
        password: '@tm@T3c'
        port: 20

           
  
