name: Chat-Auto

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
        
    - name: Deploy para o servidor CentOS
      uses: wlixcc/SFTP-Deploy-Action@v1.2.4

      with:
            username: root
            server: 10.251.1.52
            port: 22
            local_path: './*'
            remote_path: '/var/www'
            sftp_only: true
            password: '@tm@T3c'
            sftpArgs: '-o ConnectTimeout=5 -o StrictHostKeyChecking=no'

           
  
